KEY_WORDS=['nature',
 'nightlife',
 'cuisine',
 'history',
 'music',
 'entertainment',
 'art',
 'theater',
 'architecture',
 'sports',
 'outdoor activities',
 'dining',
 'museums',
 'shopping',
 'bars',
 'culture']

KEY_WORD_DIC={'Mixed drinks': ['nightlife', 'bars'],
 'alcohol': ['nightlife', 'bars'],
 'alcoholic drinks': ['nightlife', 'bars'],
 'andes': ['nature'],
 'aquatic mammals': ['nature'],
 'architectural elements': ['architecture',
  'museums',
  'culture',
  'culture',
  'history'],
 'architecture': ['architecture', 'museums', 'culture', 'culture', 'history'],
 'art': ['museums', 'art', 'culture', 'culture', 'history'],
 'art media': ['culture'],
 'arts': ['museums', 'art', 'culture', 'culture'],
 'beach': ['nature', 'sports', 'outdoor activities'],
 'brewing': ['nightlife', 'bars'],
 'christian architecture': ['architecture',
  'museums',
  'culture',
  'culture',
  'history'],
 'cocktails': ['nightlife', 'bars'],
 'cooking': ['cuisine'],
 'cuisine': ['cuisine'],
 'culture': ['culture'],
 'dining': ['cuisine'],
 'drinks': ['nightlife', 'bars'],
 'ecoregions': ['nature', 'outdoor activities'],
 'ethnic groups': ['history'],
 'european architecture': ['architecture',
  'museums',
  'culture',
  'culture',
  'history'],
 'fermented Drinks': ['bars'],
 'fermented drinks': ['nightlife'],
 'food and drink': ['cuisine', 'dining'],
 'food and drink preparation': ['cuisine'],
 'food industry': ['cuisine'],
 'forests': ['nature', 'sports', 'outdoor activities'],
 'historical': ['history'],
 'hospitality industry': ['shopping'],
 'marketplace': ['shopping'],
 'mountain': ['nature', 'outdoor activities'],
 'mountains': ['nature', 'outdoor activities'],
 'museum': ['museums', 'culture', 'history'],
 'music': ['culture', 'entertainment', 'music'],
 'nature': ['nature', 'outdoor activities'],
 'nightclub': ['nightlife', 'bars'],
 'outdoor recreation': ['nature'],
 'palace architecture': ['architecture',
  'museums',
  'culture',
  'culture',
  'history'],
 'performing arts': ['art', 'culture', 'entertainment', 'theater'],
 'pub': ['nightlife', 'bars'],
 'recreation': ['nature'],
 'religious behavior and experience': ['culture', 'history'],
 'restaurant': ['cuisine', 'dining'],
 'retail': ['shopping'],
 'shopping': ['shopping'],
 'sports': ['nature', 'sports'],
 'theater': ['entertainment', 'theater'],
 'tourist activities': ['nature', 'sports'],
 'visual art': ['museums', 'art', 'culture', 'culture'],
 'visual arts': ['museums', 'art', 'culture', 'culture'],
 'wealth': ['shopping']}