# Generated by Django 2.2.5 on 2020-03-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_origininfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[(0, 'Not Interested'), (1, 'A little Interested'), (2, 'Somewhat'), (3, 'Very'), (4, '4'), (5, '5')], max_length=1),
        ),
    ]
