# Generated by Django 2.2.5 on 2020-03-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_auto_20200309_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='origininfo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
