# Generated by Django 2.2.5 on 2020-03-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_auto_20200311_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='origininfo',
            name='answer',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1),
            preserve_default=False,
        ),
    ]
