# Generated by Django 2.2.5 on 2020-03-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_origininfo_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='origininfo',
            name='num_travelers',
            field=models.IntegerField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
