# Generated by Django 2.2.5 on 2020-03-12 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_auto_20200312_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='origininfo',
            name='date',
        ),
        migrations.AddField(
            model_name='origininfo',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='origininfo',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
