# Generated by Django 2.2.5 on 2020-03-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0011_auto_20200312_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='origininfo',
            name='duration',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='origininfo',
            name='location',
            field=models.CharField(default='Chicago', max_length=20),
        ),
    ]
